### ISSUE TITLE
Outside background not turn dark

### ISSUE THREAD

**Issue by JimmyNi** [chathuralakmal/AndroidImagePopup#10]
Cannot make outside window dimmer and how to make roundcorner for the imagepopup view?

**Comment by chathuralakmal** [comment]
@JimmyNi Thank you for pointing that out. will check on that.

**Comment by adin234** [comment]
was removed in this commit https://github.com/chathuralakmal/AndroidImagePopup/commit/b4c4bdd36b7c18e064364c522a5cb2d35882925c#diff-985066258fa911d271642901d2be79ecR155
