### ISSUE TITLE
What is the unit of window size.

### ISSUE THREAD

**Issue by HarrrrryLi** [chathuralakmal/AndroidImagePopup#20]
I try to set the window size as the full screen. But it doesn't work, it seems the half of the screen.Here's the code.
` final ImagePopup imagePopup = new ImagePopup(getActivity());
        imagePopup.setWindowWidth(Resources.getSystem().getDisplayMetrics().widthPixels);
        imagePopup.setWindowHeight(Resources.getSystem().getDisplayMetrics().heightPixels);
        imagePopup.setBackgroundColor(Color.BLACK);
        imagePopup.setHideCloseIcon(true);
        imagePopup.setImageOnClickClose(true);
        imagePopup.initiatePopup(imageView.getDrawable());`

**Comment by chathuralakmal** [comment]
Hi, thank you for pointing it out. it has fixed in the new release. 
`com.github.chathuralakmal:AndroidImagePopup:1.2`
