### ISSUE TITLE
Make function to auto fit the screen 

### ISSUE THREAD

**Issue by Abdelsattar** [chathuralakmal/AndroidImagePopup#21]
think the lib need to add function to auto fit whole screen and it take boolean to check if make it or not 

this code will  get the width and height for the screen 

` DisplayMetrics displayMetrics = new DisplayMetrics();
            ((Activity) context).getWindowManager().getDefaultDisplay().getMetrics(displayMetrics);
            int height = displayMetrics.heightPixels;
            int width = displayMetrics.widthPixels;`

i'm busy nowadays if i got free and you didn't make it yet i hope i will make it or it is already exist and i don't know 

please mark this issue as enhancement i don't know how , i think it can made by the author only

**Comment by chathuralakmal** [comment]
Thank you for the idea. I'll do the implementation.

**Comment by Abdelsattar** [comment]
i did it in my app and it's awesome
the pic is [Here ](https://goo.gl/VkjM8h)

**Comment by chathuralakmal** [comment]
Ah great. i made the changes in library.  :)
