### ISSUE TITLE
java.lang.ClassCastException: android.app.ContextImpl cannot be cast to android.app.Activity

### ISSUE THREAD

**Issue by fcaza** [chathuralakmal/AndroidImagePopup#22]
when the main activity that shows the popup in a AppCompatActivity, there's the following ex:

java.lang.ClassCastException: android.app.ContextImpl cannot be cast to android.app.Activity
                                                                    at com.ceylonlabs.imageviewpopup.ImagePopup.viewPopup(ImagePopup.java:228)

**Comment by chathuralakmal** [comment]
Can you show me the implementation code?
