### ISSUE TITLE
Problems with Picasso

### ISSUE THREAD

**Issue by djbenbe** [chathuralakmal/AndroidImagePopup#25]
the app blocks if I put this in it.
imagePopup.initiatePopupWithPicasso(messages.getMessage());
I've already tried everything.

**Comment by Abdelsattar** [comment]
what is the error message ? 
and what is the getMessage() ?

**Comment by djbenbe** [comment]
the photo is removed from the Message adapter from the recyclerView.

**Comment by Abdelsattar** [comment]
can you explain how and share screenshot and code ?

**Comment by dev-graduan** [comment]
I got this error

```
E/UncaughtException: java.lang.NoSuchMethodError: No static method 
with(Landroid/content/Context;)Lcom/squareup/picasso/Picasso; in class 
Lcom/squareup/picasso/Picasso; or its super classes (declaration of 
'com.squareup.picasso.Picasso' appears
```
My code is

```
final ImagePopup imagePopup = new ImagePopup(activity);
        imagePopup.initiatePopupWithPicasso(image);
```

**Comment by keitheyre** [comment]
This issue is because Picasso library was updated and this uses an older version that supports the .get() method, not the with() method.

**Comment by chathuralakmal** [comment]
Project updated with latest library version. please get the latest version of the project
