### ISSUE TITLE
full size image

### ISSUE THREAD

**Issue by sanyamjain65** [chathuralakmal/AndroidImagePopup#3]
even after setting imagePopup.setWindowWidth(0);
        imagePopup.setWindowHeight(0);
Image opens up occupying the full activity

**Comment by chathuralakmal** [comment]
What is the device model? is it a tab?

**Comment by sanyamjain65** [comment]
It's Moto g3

**Comment by chathuralakmal** [comment]
Try again with latest release. i have did some changes in latest release.
com.github.chathuralakmal:AndroidImagePopup:1.0.5

**Comment by sanyamjain65** [comment]
Ok
