### ISSUE TITLE
Picasso issue

### ISSUE THREAD

**Issue by brendanosborne** [chathuralakmal/AndroidImagePopup#31]
When using imagePopup.initiatePopupWithPicasso(fileUrl) I am receiving this fatal exception:

`java.lang.NoSuchMethodError: No static method with(Landroid/content/Context;)Lcom/squareup/picasso/Picasso; in class Lcom/squareup/picasso/Picasso; or its super classes (declaration of 'com.squareup.picasso.Picasso' appears in /data/app/com.removed.removed-m5CwqzHTFNXBaULIcLeNRQ==/split_lib_dependencies_apk.apk!classes2.dex)
        at com.ceylonlabs.imageviewpopup.ImagePopup.initiatePopupWithPicasso(ImagePopup.java:143)
        at com.removed.removed.fragments.LiveFragment$setImage$1.onClick(LiveFragment.kt:366)`

I am using 'com.squareup.picasso:picasso:2.71828'

The library is working fine when I use imagePopup.initiatePopup(addMediaButton.drawable)

**Comment by brendanosborne** [comment]
It looks like AndroidImagePopup is tying to use Picasso.with
`Picasso.with(this.context).load(imageUrl).into(this.imageView);`

The Picasso library changed from with to get a few versions back:
https://github.com/square/picasso/commit/e7e919232fe2b15772a7fcd9e15ead2304c66fae

**Comment by Abdelsattar** [comment]
we are using   
  compile 'com.squareup.picasso:picasso:2.5.2'
so if you downgrade to that version it will work

**Comment by firecatmusic** [comment]
> we are using
> compile 'com.squareup.picasso:picasso:2.5.2'
> so if you downgrade to that version it will work

still not workin, i had same issue btw

**Comment by chathuralakmal** [comment]
Project updated with latest Picasso Version. Please use the latest version.
