### ISSUE TITLE
Incompatible with Glide 4.8.0

### ISSUE THREAD

**Issue by emouawad** [chathuralakmal/AndroidImagePopup#33]
initiatePopupWithGlide Exception

**Comment by monsterbrain** [comment]
Me too having this error .

java.lang.NoSuchMethodError: No virtual method into(Landroid/widget/ImageView;)Lcom/bumptech/glide/request/target/Target; in class Lcom/bumptech/glide/RequestBuilder; or its super classes (declaration of 'com.bumptech.glide.RequestBuilder' appears in

**Comment by chathuralakmal** [comment]
Project Updated with Latest Glide Versions. Use Latest Version
