### ISSUE TITLE
setwindow dimensions not working

### ISSUE THREAD

**Issue by android-dataticket** [chathuralakmal/AndroidImagePopup#4]
image pops up as a very tiny image in the center of the screen no matter what is defined in setwindowheight/setwindowwidth

using a galaxy note 5

**Comment by android-dataticket** [comment]
so it appears that the size was affected by the inSampleSize that I was makign the bitmap with.. 

setwindowheight/width still have no effect, and also setRotation has no effect.. anything Im doing wrong?

**Comment by chathuralakmal** [comment]
Thank you for notifiying the issue. there was an issue in setting up setWidth and setHeight. now it should be working. try latest `compile 'com.github.chathuralakmal:AndroidImagePopup:1.0.6'`

**Comment by android-dataticket** [comment]
setdimensions works not but I don't think setRotation is doing anything still

**Comment by chathuralakmal** [comment]
setRotation not implemented in this library yet. thanks for concerning.

**Comment by princeHago** [comment]
i'm using 1.0.7 version and the image not match with setwindowheight/setwindowwidth

**Comment by chathuralakmal** [comment]
@princeHago please update to 1.0.8 that problem has fixed on it. you dont have to do any changes just update.

**Comment by princeHago** [comment]
many thanks

**Comment by chathuralakmal** [comment]
to make popup full screen you have to get device screen width and height. like below
```
     imagePopup.setWindowHeight(Resources.getSystem().getDisplayMetrics().heightPixels);
        imagePopup.setWindowWidth(Resources.getSystem().getDisplayMetrics().widthPixels);
```
