### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by AlbertoMrFz** [chathuralakmal/AndroidImagePopup#5]
Android version: API 21
AndroidImagePopup version: 1.0.6
Error: java.lang.OutOfMemoryError
Image size: 3.5MB

Code: (Is in fragment)
`ImagePopUp imagePopup = new ImagePopup(Avisos.getActivity());
imagePopup.setBackgroundColor(Color.BLACK);
imagePopup.setWindowWidth(800);
imagePopup.setWindowHeight(800);
imagePopup.setHideCloseIcon(true);
imagePopup.setImageOnClickClose(true);
imageView = new ImageView(getActivity());

filePath = data.getData();

imagePopup.setImageURI(filePath);`

**Comment by chathuralakmal** [comment]
Hi, thank you for showing the error. Currently this library only support the below method. you cannot use setImageURI.

imagePopup.initiatePopup(imageView.getDrawable());

ill add it soon as future improvement.
