### ISSUE TITLE
java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.view.WindowManager$LayoutParams

### ISSUE THREAD

**Issue by TSG9876** [chathuralakmal/AndroidImagePopup#8]
casting error at  at com.ceylonlabs.imageviewpopup.ImagePopup.initiatePopup(ImagePopup.java:156)

 /** Background dim part **/
            WindowManager windowManager = (WindowManager) context.getSystemService(Context.WINDOW_SERVICE);
            **WindowManager.LayoutParams layoutParams = (WindowManager.LayoutParams) layout.getLayoutParams();**
            layoutParams.flags = WindowManager.LayoutParams.FLAG_DIM_BEHIND;
            layoutParams.dimAmount = 0.3f;
            windowManager.updateViewLayout(layout, layoutParams);

        }catch (Exception e){
            e.printStackTrace();
}

**Comment by chathuralakmal** [comment]
I have looked into the problem. i have removed the BackgroundDimPart until finding good replacement for it. please use 1.0.7 version. increased the Responsive

**Comment by TSG9876** [comment]
thanks, will test and see if the exception removed.
