### ISSUE TITLE
PopUpWindow Dimension -Not working

### ISSUE THREAD

**Issue by TSG9876** [chathuralakmal/AndroidImagePopup#9]
I noticed that the default popupwindow size  always retain the default size even if the windows dimension were set .
imagePopup.setWindowWidth(xxx);
 imagePopup.setWindowHeight(xxx);

Line 127   _**popupWindow = new PopupWindow(layout, (int)(width*.8),(int)(height*.6), true);**_

**Comment by chathuralakmal** [comment]
Oh. made a mistake on previous version. Dimension is fixed now.

**Comment by TSG9876** [comment]
thanks, it is updated in version 1.0.7?

**Comment by chathuralakmal** [comment]
No. please update to 1.0.8 . i guess we cant add new updates to existing version. Thanks

**Comment by TSG9876** [comment]
thanks , I have tested , it is working  fine now , thanks you so much for your support and quick response.

**Comment by chathuralakmal** [comment]
Thank you very much for showing me the errors.
